# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.define :docker1 do |docker1|
        docker1.vm.box = "docker-box-1"
        docker1.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box"
        docker1.vm.network "forwarded_port", guest: 80, host:58064
        docker1.vm.network "forwarded_port", guest: 4243, host: 4264
    end
 end