# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.define :dockerCOS653 do |dockerCOS653|
        dockerCOS653.vm.box = "docker-box-CentOS-6.5.3"
        dockerCOS653.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box"
        dockerCOS653.vm.network "forwarded_port", guest: 80, host:58064
        dockerCOS653.vm.network "forwarded_port", guest: 4243, host: 4264
    end
    config.vm.provision :shell, path: "bootstrap.sh"
 end
 