# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.define :dockerCOS7 do |dockerCOS7|
        dockerCOS7.vm.box = "docker-box-CentOS-7.0"
        dockerCOS7.vm.box_url = "https://f0fff3908f081cb6461b407be80daf97f07ac418.googledrive.com/host/0BwtuV7VyVTSkUG1PM3pCeDJ4dVE/centos7.box"
        dockerCOS7.vm.network "forwarded_port", guest: 80, host:58067
        dockerCOS7.vm.network "forwarded_port", guest: 4243, host: 4267
    end
    config.vm.provision :shell, path: "bootstrap.sh"
 end